# Generated by Django 5.0.2 on 2024-03-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_price', models.IntegerField()),
                ('book_category', models.CharField(max_length=100)),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='api.author')),
            ],
        ),
    ]
